# Generated by Django 5.1.2 on 2025-08-27 10:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Brand name (e.g., WP Rocket, RankMath)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly brand identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Brand description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this brand is active in the system",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LicenseKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Unique license key identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="Customer email address", max_length=254
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this license key is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        help_text="Brand that owns this license key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_keys",
                        to="licenses.brand",
                    ),
                ),
            ],
            options={
                "db_table": "license_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly product identifier", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Product description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this product is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        help_text="Brand that owns this product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="licenses.brand",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["brand__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="valid",
                        help_text="Current status of the license",
                        max_length=20,
                    ),
                ),
                (
                    "seats",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of seats/activations allowed",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(help_text="When this license expires"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license_key",
                    models.ForeignKey(
                        help_text="License key this license belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="licenses.licensekey",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this license grants access to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="licenses.product",
                    ),
                ),
            ],
            options={
                "db_table": "licenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Activation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_identifier",
                    models.CharField(
                        help_text="Unique identifier for the instance (URL, hostname, machine ID)",
                        max_length=500,
                    ),
                ),
                (
                    "instance_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of instance (website, app, CLI, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this activation is currently active",
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license",
                    models.ForeignKey(
                        help_text="License being activated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="licenses.license",
                    ),
                ),
            ],
            options={
                "db_table": "activations",
                "ordering": ["-activated_at"],
                "indexes": [
                    models.Index(
                        fields=["instance_identifier"],
                        name="activations_instanc_9c1fa8_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="activations_is_acti_ae5a13_idx"
                    ),
                    models.Index(
                        fields=["license"], name="activations_license_f290aa_idx"
                    ),
                ],
                "unique_together": {("license", "instance_identifier")},
            },
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(
                fields=["customer_email"], name="license_key_custome_dc5384_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(fields=["brand"], name="license_key_brand_i_f7fb49_idx"),
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(
                fields=["is_active"], name="license_key_is_acti_bf3982_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("brand", "slug")},
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["status"], name="licenses_status_c60f55_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["expiration_date"], name="licenses_expirat_d1da69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["product"], name="licenses_product_e3fbd8_idx"),
        ),
    ]
