# Generated by Django 5.1.2 on 2025-08-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="deactivation_reason",
            field=models.TextField(
                blank=True, help_text="Reason for deactivation if applicable"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="cancellation_reason",
            field=models.TextField(
                blank=True, help_text="Reason for cancellation if applicable"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, help_text="When the license was cancelled", null=True
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="original_expiration_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Original expiration date before renewal",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="renewal_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this license has been renewed"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="suspended_at",
            field=models.DateTimeField(
                blank=True, help_text="When the license was suspended", null=True
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="suspension_reason",
            field=models.TextField(
                blank=True, help_text="Reason for suspension if applicable"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="status",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("suspended", "Suspended"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("pending", "Pending"),
                    ("renewed", "Renewed"),
                ],
                default="valid",
                help_text="Current status of the license",
                max_length=20,
            ),
        ),
    ]
